/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ddnd;

import java.io.*;
import java.net.*;
import java.util.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author dan
 */
public class NewJFrame extends javax.swing.JFrame implements Runnable {
    static MulticastSocket socket;
    static InetAddress address;
    static DatagramPacket sendPacket;
    static DatagramPacket recvPacket;
    public int playerID = 0;
    
    // USED FOR PARSING DATA FROM SERVER
        public void run() {
        try{
            System.out.println("Thread running.");
            InetAddress address = InetAddress.getByName("230.0.0.1");
            socket = new MulticastSocket(4446);
            socket.joinGroup(address);
            while(true) {
                String received = recvString();
                System.out.println("BROADCAST (njf): " + received);
                String[] str = new String[3];
                str = received.split(";");
                //System.out.println("str[0] = "+str[0]+" / str[1] = "+str[1]);
                switch(str[0]) {
                    case "output":
                        System.out.println("Setting output area");
                        clientFrame.OutputLogArea.setText(str[1]);
                        break;
                    case "map":
                        System.out.println("Setting map area");
                        clientFrame.mapTextArea.setText(str[1]);
                        break;
                    default:
                        System.out.println(str[0]);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mapTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        statsArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        OutputLogArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mapTextArea.setEditable(false);
        mapTextArea.setBackground(new java.awt.Color(0, 0, 0));
        mapTextArea.setColumns(20);
        mapTextArea.setFont(new java.awt.Font("Monospaced", 0, 35)); // NOI18N
        mapTextArea.setForeground(new java.awt.Color(255, 255, 255));
        mapTextArea.setLineWrap(true);
        mapTextArea.setRows(8);
        mapTextArea.setAutoscrolls(false);
        mapTextArea.setCaretColor(new java.awt.Color(240, 240, 240));
        mapTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mapTextAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mapTextAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(mapTextArea);

        statsArea.setBackground(new java.awt.Color(0, 0, 0));
        statsArea.setColumns(20);
        statsArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        statsArea.setForeground(new java.awt.Color(255, 255, 255));
        statsArea.setLineWrap(true);
        statsArea.setRows(6);
        statsArea.setWrapStyleWord(true);
        statsArea.setFocusable(false);
        jScrollPane2.setViewportView(statsArea);

        logArea.setBackground(new java.awt.Color(0, 0, 0));
        logArea.setColumns(20);
        logArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        logArea.setForeground(new java.awt.Color(255, 255, 255));
        logArea.setLineWrap(true);
        logArea.setRows(1);
        logArea.setWrapStyleWord(true);
        logArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                logAreaKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(logArea);

        OutputLogArea.setBackground(new java.awt.Color(0, 0, 0));
        OutputLogArea.setColumns(20);
        OutputLogArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        OutputLogArea.setForeground(new java.awt.Color(255, 255, 255));
        OutputLogArea.setLineWrap(true);
        OutputLogArea.setRows(5);
        OutputLogArea.setFocusable(false);
        jScrollPane4.setViewportView(OutputLogArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mapTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mapTextAreaKeyPressed
        try {
            switch(evt.getKeyCode()) {
                   case KeyEvent.VK_UP:
                       sendString("command;up");
                       break;
                   case KeyEvent.VK_DOWN:
                       sendString("command;down");
                       break;
                   case KeyEvent.VK_LEFT:
                       sendString("command;left");
                       break;
                   case KeyEvent.VK_RIGHT:
                       sendString("command;right");
                       break;
            }
            // wait for map and generate it
            //String map = this.recvString();
            //this.mapTextArea.setText(map);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mapTextAreaKeyPressed

    private void mapTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mapTextAreaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mapTextAreaKeyReleased

    // USED TO SEND INPUT TO THE SERVER IN THE FORM OF WORDS
    private void logAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logAreaKeyPressed

    }//GEN-LAST:event_logAreaKeyPressed
    
    private void logAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logAreaKeyReleased
        try {
            switch(evt.getKeyCode()) {
                   case KeyEvent.VK_ENTER:
                       String request = logArea.getText().replaceAll("\n", "");
                       String username = request + ";";
                       String str = "username;"+username;
                       this.sendString(str);
                       this.logArea.setText("");
                       this.logArea.setCaretPosition(0);
                       Random rand = new Random();
                       this.playerID = rand.nextInt();
                       //String yep = recvString();
                       //yep += this.playerID;
                       //this.OutputLogArea.setText(yep);
                       break;
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_logAreaKeyReleased

    public void outputLogListener(String string) {
        this.OutputLogArea.setText(string);
    }
    
    /**
     * @param args the command line arguments
     */
    
    // method for sending a string packet to the UDP server. works globally (mainly using for the formKeyReleased method).
    public void sendString(String string) throws IOException { //i love java
        byte[] byteArray = new byte[256];
        byteArray = string.getBytes();
        sendPacket = new DatagramPacket(byteArray, byteArray.length, address, 4445);
        socket.send(sendPacket);
        System.out.println("Sent packet.");
    }
    
    /* receive a string from the server. The string is going to contain ALL information necessary to provide the server with the following:
    - 
    */
    public String recvString() throws IOException {
        byte[] buf = new byte[256];
        recvPacket = new DatagramPacket(buf, buf.length);
        System.out.println("Waiting for packet.");
        socket.receive(recvPacket);
        System.out.println("Received packet.");
        String received = new String(recvPacket.getData(), 0, recvPacket.getLength());
        return received;
    }
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*NewJFrame*/ clientFrame = new NewJFrame();
                clientFrame.setLocationRelativeTo(null);
                clientFrame.setVisible(true);
                clientFrame.mapTextArea.setText("starting text");
                try {
                    address = InetAddress.getByName("230.0.0.1");
                    socket = new MulticastSocket(4446);
                    socket.joinGroup(address);
                    //MulticastClient listener = new MulticastClient();
                    NewJFrame listener = new NewJFrame();
                    Thread thread1 = new Thread(listener);
                    thread1.start();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            //socket.leaveGroup(address);
            //socket.close(); 
            }
        });
    }

    static NewJFrame clientFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea OutputLogArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea logArea;
    private javax.swing.JTextArea mapTextArea;
    private javax.swing.JTextArea statsArea;
    // End of variables declaration//GEN-END:variables
}